### ISSUE TITLE
Videos not removing.

### ISSUE THREAD

**Issue by DemonAMVs** [Mattie432/YouTweak#15]
As the title says, I click Remove Video the button will animate but the video will not remove at all, same applies for Remove watched videos both manual and automatic.

All other features such as Change the YouTube icon URL, redirect youtube.com and autolike still work.  
I have not tested clear all videos.

I am using the latest version of chrome Version 46.0.2490.71 m, I disabled all other addons and extensions to rule out conflicts.

**Comment by Mattie432** [comment]
Hi, i suspect YouTube are updating their homepage layout again. Unfortunately this has not been rolled out for me so my extension is still working fine & I cannot test/fix. Would you be able to provide a copy of your homepage for me to test on? EIther zip the files and post here or send them privately to matt@mattie432.com

1. Go to YouTube homepage.
2. Click menu -> More tools -> Save Page as (or Ctrl + S)
3. A file & folder will be created at the destination of your choosing.
4. Zip both files (highlight both -> right click -> send to -> compressed folder)

Thanks for your help!

**Comment by Mattie432** [comment]
Just to keep people updated I have recieved a copy of the updated homepage and will look into fixing it tomorrow.

**Comment by Mattie432** [comment]
Could you please test the pre-release build [here](https://github.com/Mattie432/YouTweak/releases/tag/3.234). Especially the "version selection" option, which should work for you when selecting 'latest' and not work when selecting 'previous'.

Thanks.

**Comment by Mattie432** [comment]
Could you please test the pre-release build again [here](https://github.com/Mattie432/YouTweak/releases/tag/3.234). Select the version 3.233. Remove watched & remove individual videos should work.

**Comment by NuBiXx** [comment]
Not working for me either. I tested the pre-release build you posted and that don't work for me either.

**Comment by Mattie432** [comment]
This issue is closed, i have opened a more recent issue [here](https://github.com/Mattie432/YouTweak/issues/21)
