### ISSUE TITLE
Can't Install Extension. Error.

### ISSUE THREAD

**Issue by rockon999** [Mattie432/YouTweak#19]
Whenever I attempt to add this plugin via the Chrome Web Store I get the following error: `Package is invalid. Details: 'Could not load javascript 'contextscripts/homepage_loadatend.js' for content script.'`. Is it possible your capitalization for homepage_loadAtEnd.js is incorrect?

**Comment by Mattie432** [comment]
Hi, yes it definitely is. This is probably left over from a large restructure a while ago. If you are able to submit a pull request to fix feel free, otherwise I shall look into it after work. Thanks.

**Comment by Mattie432** [comment]
Closed, full refactor of the code.
