### ISSUE TITLE
YouTube homepage update 24-11-15

### ISSUE THREAD

**Issue by Mattie432** [Mattie432/YouTweak#21]
YouTube appears to have updated their homepage again in some regions. Issue relating to the new update.

[@NuBiXx originally alerted in another thread]

**Comment by Mattie432** [comment]
@NuBiXx Could you send me a copy of your homepage so I can test & work out a fix. Instructions are [here](https://github.com/Mattie432/YouTweak/wiki/Sending-a-copy-of-the-webpage-for-debugging). Thanks.

**Comment by NuBiXx** [comment]
I have emailed the files to you. Thanks

**Comment by NuBiXx** [comment]
No fix yet?

**Comment by Mattie432** [comment]
Closed, code fully refactored.
