### ISSUE TITLE
options.html references deleted combo box

### ISSUE THREAD

**Issue by darthwalsh** [Mattie432/YouTweak#38]
In the [options help text](https://github.com/Mattie432/YouTweak/blob/master/src/chrome/optionsPage/options.html#L218) there's a mention of a version combo box... but that combo box doesn't exist right now. (The HTML was [deleted](https://github.com/Mattie432/YouTweak/commit/9981ca1f7543e5ca3c2dd28e653c674e270f5d04#diff-a6ce31333dce17a5085ddc4fd193e571L56) a while ago.)

Should the combo box be re-enabled, or should the help-text get cleaned up?

**Comment by Mattie432** [comment]
Cheers, cleaned up in ea7e60e6f3b4f6eef2c5de428ed2130944664724
