### ISSUE TITLE
After youtube update

### ISSUE THREAD

**Issue by Zedus112** [Mattie432/YouTweak#4]
Update pls, after another change in youtube interface - doesn't work
[no buttons, dont hide watched etc]

**Comment by Mattie432** [comment]
Hi, sorry to hear you are having issues. I cannot see any problems on my end with youtube so it would seem to me that you could be accessing an 'A/B testing' build of the homepage. 

I could suggest clearing cookies (or sign in in incognito) to check if this can be reversed. Or try accessing a different geographic youtube (youtube.co.uk for example) to see if this is the case. If so then there is not a lot I can do to fix it as (based off previous peoples messages) youtube tends to revert these changes after a few days.

**Comment by Mattie432** [comment]
Thanks for the heads up, looks like the update was site wide and I recieved it a few hours after you. Should be fixed with this version which im uploading to chrome store now.
