### ISSUE TITLE
"Added to liked videos" popup are on a endless loop when using "autolike".

### ISSUE THREAD

**Issue by BabaBooey84** [Mattie432/YouTweak#6]
Hey Mattie

Awesome extension, but I discovered a small bug.

When using "Autolike", the popup on youtube are on a endless loop, pops up again and again.

Chrome version: 41.0.2272.118

![image](https://cloud.githubusercontent.com/assets/11920132/7111234/3e216268-e1bd-11e4-9f50-e4e2a9588be1.png)

**Comment by Mattie432** [comment]
Closed, feature removed.
