### ISSUE TITLE
Broken Autolike

### ISSUE THREAD

**Issue by BurningNight** [Mattie432/YouTweak#8]
Recently there has been an issue with the auto like system. Every time I watch a video that gets auto liked, I continuously get the notification that I have liked the video (The little blue check mark at the top that says "added to liked videos". It seems like YouTweak is liking the video over and over and over again, rather than just liking it once. It's not the biggest deal, but it gets annoying seeing that little blue check mark flash in the upper left corner every 3 seconds.

Also, hey, YouTweak is an awesome extensions that I really enjoy. So high five. o/

**Comment by Mattie432** [comment]
Closed, feature removed.
