### ISSUE TITLE
Autohide >3rd page is broken

### ISSUE THREAD

**Issue by Zedus112** [Mattie432/YouTweak#9]
Autohide (Automatically remove watched videos) works on 1st & 2nd page well, but after 2nd click on "Load more" - doesn't hide videos. if disable "Automatically remove watched videos", and manually click on "Remove watched videos" - works fine everywhere.
p.s. sry for my bad english =)

**Comment by Mattie432** [comment]
Closed. Fixed when code cleanup occurred.
